<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="34" total="70" passed="36">
  <reporter-output>
  </reporter-output>
  <suite name="Suite" duration-ms="976175" started-at="2019-12-09T11:26:41Z" finished-at="2019-12-09T11:42:57Z">
    <groups>
    </groups>
    <test name="Test" duration-ms="976175" started-at="2019-12-09T11:26:41Z" finished-at="2019-12-09T11:42:57Z">
      <class name="yjp.Distribution">
        <test-method status="PASS" signature="doBeforeClass()[pri:0, instance:yjp.Distribution@3f3afe78]" name="doBeforeClass" is-config="true" duration-ms="10685" started-at="2019-12-09T19:41:56Z" finished-at="2019-12-09T19:42:07Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- doBeforeClass -->
        <test-method status="PASS" signature="setup()[pri:0, instance:yjp.Distribution@3f3afe78]" name="setup" is-config="true" duration-ms="20187" started-at="2019-12-09T19:42:07Z" description="登录" finished-at="2019-12-09T19:42:27Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method status="PASS" signature="input()[pri:0, instance:yjp.Distribution@3f3afe78]" name="input" duration-ms="7388" started-at="2019-12-09T19:42:27Z" description="在订单编号查询的输入框中输入" finished-at="2019-12-09T19:42:35Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- input -->
        <test-method status="FAIL" signature="invitation()[pri:0, instance:yjp.Distribution@3f3afe78]" name="invitation" duration-ms="12665" started-at="2019-12-09T19:42:35Z" description="选择三级下线，点击快去邀请好友" finished-at="2019-12-09T19:42:47Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at org.testng.Assert.assertTrue(Assert.java:52)
	at yjp.Distribution.invitation(Distribution.java:38)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:822)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1130)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:113)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:206)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:177)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- invitation -->
        <test-method status="FAIL" signature="rebate()[pri:0, instance:yjp.Distribution@3f3afe78]" name="rebate" duration-ms="4199" started-at="2019-12-09T19:42:47Z" description="选择一个会员，点击查看返利订单" finished-at="2019-12-09T19:42:51Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at org.testng.Assert.assertTrue(Assert.java:52)
	at yjp.Distribution.rebate(Distribution.java:30)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:822)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1130)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:113)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:206)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:177)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- rebate -->
        <test-method status="PASS" signature="doAfterMethod()[pri:0, instance:yjp.Distribution@3f3afe78]" name="doAfterMethod" is-config="true" duration-ms="6030" started-at="2019-12-09T19:42:51Z" finished-at="2019-12-09T19:42:57Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- doAfterMethod -->
      </class> <!-- yjp.Distribution -->
      <class name="yjp.VirtualOrder">
        <test-method status="PASS" signature="doBeforeClass()[pri:0, instance:yjp.VirtualOrder@880ec60]" name="doBeforeClass" is-config="true" duration-ms="8199" started-at="2019-12-09T19:39:48Z" finished-at="2019-12-09T19:39:56Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- doBeforeClass -->
        <test-method status="PASS" signature="setup()[pri:0, instance:yjp.VirtualOrder@880ec60]" name="setup" is-config="true" duration-ms="40933" started-at="2019-12-09T19:39:56Z" description="登录" finished-at="2019-12-09T19:40:37Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method status="FAIL" signature="Enquiry_Fail()[pri:0, instance:yjp.VirtualOrder@880ec60]" name="Enquiry_Fail" duration-ms="7886" started-at="2019-12-09T19:40:37Z" description="查询订单失败，输入错误信息" finished-at="2019-12-09T19:40:45Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at org.testng.Assert.assertTrue(Assert.java:52)
	at yjp.VirtualOrder.Enquiry_Fail(VirtualOrder.java:121)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:822)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1130)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:113)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:206)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:177)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Enquiry_Fail -->
        <test-method status="PASS" signature="Enquiry_OrderByID()[pri:0, instance:yjp.VirtualOrder@880ec60]" name="Enquiry_OrderByID" duration-ms="7284" started-at="2019-12-09T19:40:45Z" description="输入订单编号，查询订单成功" finished-at="2019-12-09T19:40:52Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Enquiry_OrderByID -->
        <test-method status="PASS" signature="Enquiry_OrderByName()[pri:0, instance:yjp.VirtualOrder@880ec60]" name="Enquiry_OrderByName" duration-ms="7943" started-at="2019-12-09T19:40:52Z" description="输入商品名称，查询订单成功" finished-at="2019-12-09T19:41:00Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Enquiry_OrderByName -->
        <test-method status="FAIL" signature="OrderDetail()[pri:0, instance:yjp.VirtualOrder@880ec60]" name="OrderDetail" duration-ms="11646" started-at="2019-12-09T19:41:00Z" description="虚拟订单，点击查看详情" finished-at="2019-12-09T19:41:12Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at org.testng.Assert.assertTrue(Assert.java:52)
	at yjp.VirtualOrder.OrderDetail(VirtualOrder.java:80)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:822)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1130)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:113)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:206)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:177)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- OrderDetail -->
        <test-method status="FAIL" signature="assessOrder_Fail1()[pri:0, instance:yjp.VirtualOrder@880ec60]" name="assessOrder_Fail1" duration-ms="19370" started-at="2019-12-09T19:41:12Z" description="评价商品失败，未进行打分" finished-at="2019-12-09T19:41:31Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at org.testng.Assert.assertTrue(Assert.java:52)
	at yjp.VirtualOrder.assessOrder_Fail1(VirtualOrder.java:56)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:822)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1130)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:113)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:206)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:177)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- assessOrder_Fail1 -->
        <test-method status="FAIL" signature="assessOrder_Fail2()[pri:0, instance:yjp.VirtualOrder@880ec60]" name="assessOrder_Fail2" duration-ms="675" started-at="2019-12-09T19:41:31Z" description="评价商品失败，未进行内容评价" finished-at="2019-12-09T19:41:32Z">
          <exception class="org.openqa.selenium.ElementClickInterceptedException">
            <message>
              <![CDATA[Element <img src="/public/images/star-off.png"> is not clickable at point (708,194) because another element <div id="layui-layer-shade1" class="layui-layer-shade"> obscures it
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:25:53'
System info: host: 'LAPTOP-GAD15EJN', ip: '169.254.0.95', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_73'
Driver info: org.openqa.selenium.firefox.FirefoxDriver
Capabilities {acceptInsecureCerts: true, browserName: firefox, browserVersion: 69.0.3, javascriptEnabled: true, moz:accessibilityChecks: false, moz:buildID: 20191009172106, moz:geckodriverVersion: 0.24.0, moz:headless: false, moz:processID: 3688, moz:profile: E:\Temp\rust_mozprofile.MNk..., moz:shutdownTimeout: 60000, moz:useNonSpecCompliantPointerOrigin: false, moz:webdriverClick: true, pageLoadStrategy: normal, platform: WINDOWS, platformName: WINDOWS, platformVersion: 10.0, rotatable: false, setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify}
Session ID: 6d85dfd1-c81e-47d9-ae12-f363293d0e3f]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.openqa.selenium.ElementClickInterceptedException: Element <img src="/public/images/star-off.png"> is not clickable at point (708,194) because another element <div id="layui-layer-shade1" class="layui-layer-shade"> obscures it
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:25:53'
System info: host: 'LAPTOP-GAD15EJN', ip: '169.254.0.95', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_73'
Driver info: org.openqa.selenium.firefox.FirefoxDriver
Capabilities {acceptInsecureCerts: true, browserName: firefox, browserVersion: 69.0.3, javascriptEnabled: true, moz:accessibilityChecks: false, moz:buildID: 20191009172106, moz:geckodriverVersion: 0.24.0, moz:headless: false, moz:processID: 3688, moz:profile: E:\Temp\rust_mozprofile.MNk..., moz:shutdownTimeout: 60000, moz:useNonSpecCompliantPointerOrigin: false, moz:webdriverClick: true, pageLoadStrategy: normal, platform: WINDOWS, platformName: WINDOWS, platformVersion: 10.0, rotatable: false, setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify}
Session ID: 6d85dfd1-c81e-47d9-ae12-f363293d0e3f
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
	at java.lang.reflect.Constructor.newInstance(Unknown Source)
	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.createException(W3CHttpResponseCodec.java:187)
	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:122)
	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:49)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:158)
	at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:83)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:552)
	at org.openqa.selenium.remote.RemoteWebElement.execute(RemoteWebElement.java:285)
	at org.openqa.selenium.remote.RemoteWebElement.click(RemoteWebElement.java:84)
	at com.webtest.core.WebDriverEngine.click(WebDriverEngine.java:154)
	at yjp.VirtualOrder.assessOrder_Fail2(VirtualOrder.java:66)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:822)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1130)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:113)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:206)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:177)
]]>
            </full-stacktrace>
          </exception> <!-- org.openqa.selenium.ElementClickInterceptedException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- assessOrder_Fail2 -->
        <test-method status="FAIL" signature="cancelOrder()[pri:0, instance:yjp.VirtualOrder@880ec60]" name="cancelOrder" duration-ms="3911" started-at="2019-12-09T19:41:32Z" description="未付款订单取消订单/立即支付" finished-at="2019-12-09T19:41:36Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at org.testng.Assert.assertTrue(Assert.java:52)
	at yjp.VirtualOrder.cancelOrder(VirtualOrder.java:96)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:822)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1130)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:113)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:206)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:177)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- cancelOrder -->
        <test-method status="FAIL" signature="selectOrder()[pri:0, instance:yjp.VirtualOrder@880ec60]" name="selectOrder" duration-ms="13332" started-at="2019-12-09T19:41:36Z" description="收货确认，评价商品，匿名进行评价成功" finished-at="2019-12-09T19:41:49Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at org.testng.Assert.assertTrue(Assert.java:52)
	at yjp.VirtualOrder.selectOrder(VirtualOrder.java:41)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:822)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1130)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:113)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:206)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:177)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- selectOrder -->
        <test-method status="PASS" signature="doAfterMethod()[pri:0, instance:yjp.VirtualOrder@880ec60]" name="doAfterMethod" is-config="true" duration-ms="7211" started-at="2019-12-09T19:41:49Z" finished-at="2019-12-09T19:41:56Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- doAfterMethod -->
      </class> <!-- yjp.VirtualOrder -->
      <class name="yjp.MyOrder">
        <test-method status="PASS" signature="doBeforeClass()[pri:0, instance:yjp.MyOrder@b684286]" name="doBeforeClass" is-config="true" duration-ms="6522" started-at="2019-12-09T19:38:15Z" finished-at="2019-12-09T19:38:21Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- doBeforeClass -->
        <test-method status="PASS" signature="setup()[pri:0, instance:yjp.MyOrder@b684286]" name="setup" is-config="true" duration-ms="40483" started-at="2019-12-09T19:38:21Z" description="登录" finished-at="2019-12-09T19:39:02Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method status="PASS" signature="Enquiry_Fail1(java.lang.String, java.lang.String)[pri:0, instance:yjp.MyOrder@b684286]" name="Enquiry_Fail1" duration-ms="3905" started-at="2019-12-09T19:39:02Z" description="查询订单失败，输入错误信息" data-provider="错误输入" finished-at="2019-12-09T19:39:06Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[2019]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[您还没有订单]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Enquiry_Fail1 -->
        <test-method status="PASS" signature="Enquiry_Fail1(java.lang.String, java.lang.String)[pri:0, instance:yjp.MyOrder@b684286]" name="Enquiry_Fail1" duration-ms="3615" started-at="2019-12-09T19:39:06Z" description="查询订单失败，输入错误信息" data-provider="错误输入" finished-at="2019-12-09T19:39:10Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[6S]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[您还没有订单]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Enquiry_Fail1 -->
        <test-method status="PASS" signature="Enquiry_Fail1(java.lang.String, java.lang.String)[pri:0, instance:yjp.MyOrder@b684286]" name="Enquiry_Fail1" duration-ms="3598" started-at="2019-12-09T19:39:10Z" description="查询订单失败，输入错误信息" data-provider="错误输入" finished-at="2019-12-09T19:39:13Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[华为]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[您还没有订单]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Enquiry_Fail1 -->
        <test-method status="FAIL" signature="Enquiry_Fail1(java.lang.String, java.lang.String)[pri:0, instance:yjp.MyOrder@b684286]" name="Enquiry_Fail1" duration-ms="3684" started-at="2019-12-09T19:39:13Z" description="查询订单失败，输入错误信息" data-provider="错误输入" finished-at="2019-12-09T19:39:17Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[ ]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[您还没有订单]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
	expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
	expected [true] but found [false]
	at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:43)
	at yjp.MyOrder.Enquiry_Fail1(MyOrder.java:64)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:822)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1130)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:113)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:206)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:177)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Enquiry_Fail1 -->
        <test-method status="PASS" signature="Enquiry_Fail1(java.lang.String, java.lang.String)[pri:0, instance:yjp.MyOrder@b684286]" name="Enquiry_Fail1" duration-ms="3760" started-at="2019-12-09T19:39:17Z" description="查询订单失败，输入错误信息" data-provider="错误输入" finished-at="2019-12-09T19:39:21Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[aaaaa]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[您还没有订单]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Enquiry_Fail1 -->
        <test-method status="PASS" signature="Enquiry_Fail2()[pri:0, instance:yjp.MyOrder@b684286]" name="Enquiry_Fail2" duration-ms="19159" started-at="2019-12-09T19:39:21Z" description="查看订单详情、选择取消订单（未付款）、点击再次购买" finished-at="2019-12-09T19:39:40Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Enquiry_Fail2 -->
        <test-method status="FAIL" signature="Enquiry_Order(java.lang.String, java.lang.String)[pri:0, instance:yjp.MyOrder@b684286]" name="Enquiry_Order" duration-ms="38" started-at="2019-12-09T19:39:40Z" description="查询订单成功" data-provider="正确输入" finished-at="2019-12-09T19:39:40Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[201909191108196628]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[华为畅想8全网通华为畅享9plus降价荣耀]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at org.testng.Assert.assertTrue(Assert.java:52)
	at yjp.MyOrder.Enquiry_Order(MyOrder.java:50)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:822)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1130)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:113)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:206)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:177)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Enquiry_Order -->
        <test-method status="FAIL" signature="Enquiry_Order(java.lang.String, java.lang.String)[pri:0, instance:yjp.MyOrder@b684286]" name="Enquiry_Order" duration-ms="33" started-at="2019-12-09T19:39:40Z" description="查询订单成功" data-provider="正确输入" finished-at="2019-12-09T19:39:40Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[201909191054416755]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[苹果7钢化膜iphone8plus手机7plus全屏全覆盖8贴膜水凝7p抗蓝光3D]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at org.testng.Assert.assertTrue(Assert.java:52)
	at yjp.MyOrder.Enquiry_Order(MyOrder.java:50)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:822)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1130)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:113)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:206)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:177)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Enquiry_Order -->
        <test-method status="FAIL" signature="Enquiry_Order(java.lang.String, java.lang.String)[pri:0, instance:yjp.MyOrder@b684286]" name="Enquiry_Order" duration-ms="42" started-at="2019-12-09T19:39:40Z" description="查询订单成功" data-provider="正确输入" finished-at="2019-12-09T19:39:40Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[欧式陶瓷花瓶时尚简约家居摆件客厅饰品小清新桌面干花瓶鲜花花器]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[201907091956495616]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at org.testng.Assert.assertTrue(Assert.java:52)
	at yjp.MyOrder.Enquiry_Order(MyOrder.java:50)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:822)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1130)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:113)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:206)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:177)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Enquiry_Order -->
        <test-method status="FAIL" signature="Enquiry_Order(java.lang.String, java.lang.String)[pri:0, instance:yjp.MyOrder@b684286]" name="Enquiry_Order" duration-ms="29" started-at="2019-12-09T19:39:40Z" description="查询订单成功" data-provider="正确输入" finished-at="2019-12-09T19:39:40Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[牛肉干]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[201907031648094298]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at org.testng.Assert.assertTrue(Assert.java:52)
	at yjp.MyOrder.Enquiry_Order(MyOrder.java:50)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:822)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1130)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:113)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:206)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:177)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Enquiry_Order -->
        <test-method status="FAIL" signature="cancelDetail()[pri:0, instance:yjp.MyOrder@b684286]" name="cancelDetail" duration-ms="226" started-at="2019-12-09T19:39:40Z" description="对未付款的订单选择立即付款" finished-at="2019-12-09T19:39:40Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at org.testng.Assert.assertTrue(Assert.java:52)
	at yjp.MyOrder.cancelDetail(MyOrder.java:104)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:822)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1130)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:113)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:206)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:177)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- cancelDetail -->
        <test-method status="FAIL" signature="cancelOrder1()[pri:0, instance:yjp.MyOrder@b684286]" name="cancelOrder1" duration-ms="3366" started-at="2019-12-09T19:39:40Z" description="取消已付款但未发货的订单" finished-at="2019-12-09T19:39:44Z">
          <exception class="org.openqa.selenium.NoSuchFrameException">
            <message>
              <![CDATA[No frame element found by name or id layui-layer-iframe1
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:25:53'
System info: host: 'LAPTOP-GAD15EJN', ip: '169.254.0.95', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_73'
Driver info: driver.version: unknown]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.openqa.selenium.NoSuchFrameException: No frame element found by name or id layui-layer-iframe1
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:25:53'
System info: host: 'LAPTOP-GAD15EJN', ip: '169.254.0.95', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_73'
Driver info: driver.version: unknown
	at org.openqa.selenium.remote.RemoteWebDriver$RemoteTargetLocator.frame(RemoteWebDriver.java:885)
	at com.webtest.core.WebDriverEngine.enterFrame(WebDriverEngine.java:77)
	at yjp.MyOrder.cancelOrder1(MyOrder.java:88)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:822)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1130)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:113)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:206)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:177)
]]>
            </full-stacktrace>
          </exception> <!-- org.openqa.selenium.NoSuchFrameException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- cancelOrder1 -->
        <test-method status="PASS" signature="changeState()[pri:0, instance:yjp.MyOrder@b684286]" name="changeState" duration-ms="509" started-at="2019-12-09T19:39:44Z" description="通过交易状态查询订单" finished-at="2019-12-09T19:39:44Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- changeState -->
        <test-method status="PASS" signature="doAfterMethod()[pri:0, instance:yjp.MyOrder@b684286]" name="doAfterMethod" is-config="true" duration-ms="3795" started-at="2019-12-09T19:39:44Z" finished-at="2019-12-09T19:39:48Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- doAfterMethod -->
      </class> <!-- yjp.MyOrder -->
      <class name="yjp.Information">
        <test-method status="PASS" signature="doBeforeClass()[pri:0, instance:yjp.Information@1e643faf]" name="doBeforeClass" is-config="true" duration-ms="6062" started-at="2019-12-09T19:29:42Z" finished-at="2019-12-09T19:29:48Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- doBeforeClass -->
        <test-method status="PASS" signature="setup()[pri:0, instance:yjp.Information@1e643faf]" name="setup" is-config="true" duration-ms="39224" started-at="2019-12-09T19:29:48Z" description="登录" finished-at="2019-12-09T19:30:27Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method status="PASS" signature="Bind_Phone()[pri:0, instance:yjp.Information@1e643faf]" name="Bind_Phone" duration-ms="11232" started-at="2019-12-09T19:30:27Z" description="更换绑定手机成功" finished-at="2019-12-09T19:30:38Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Bind_Phone -->
        <test-method status="PASS" signature="goToSecurity()[pri:0, instance:yjp.Information@1e643faf]" name="goToSecurity" duration-ms="7921" started-at="2019-12-09T19:30:38Z" description="跳转到安全设置" finished-at="2019-12-09T19:30:46Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- goToSecurity -->
        <test-method status="PASS" signature="modify_Birthday(java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:yjp.Information@1e643faf]" name="modify_Birthday" duration-ms="14839" started-at="2019-12-09T19:30:46Z" description="修改个人信息,生日" data-provider="birthday" finished-at="2019-12-09T19:31:01Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[E:\\1.jpeg]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[测试账号1]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[1]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[1999-10-04]]>
              </value>
            </param>
            <param index="4">
              <value>
                <![CDATA[操作成功]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- modify_Birthday -->
        <test-method status="FAIL" signature="modify_Birthday(java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:yjp.Information@1e643faf]" name="modify_Birthday" duration-ms="15171" started-at="2019-12-09T19:31:01Z" description="修改个人信息,生日" data-provider="birthday" finished-at="2019-12-09T19:31:16Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[E:\\1.jpeg]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[测试账号2]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[2]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[1840-11-1]]>
              </value>
            </param>
            <param index="4">
              <value>
                <![CDATA[操作失败]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
	expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
	expected [true] but found [false]
	at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:43)
	at yjp.Information.modify_Birthday(Information.java:88)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:822)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1130)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:113)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:206)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:177)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- modify_Birthday -->
        <test-method status="FAIL" signature="modify_Birthday(java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:yjp.Information@1e643faf]" name="modify_Birthday" duration-ms="14916" started-at="2019-12-09T19:31:16Z" description="修改个人信息,生日" data-provider="birthday" finished-at="2019-12-09T19:31:31Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[E:\\1.jpeg]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[测试账号3]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[3]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[2022-1-1]]>
              </value>
            </param>
            <param index="4">
              <value>
                <![CDATA[操作失败]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
	expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
	expected [true] but found [false]
	at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:43)
	at yjp.Information.modify_Birthday(Information.java:88)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:822)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1130)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:113)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:206)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:177)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- modify_Birthday -->
        <test-method status="FAIL" signature="modify_Birthday(java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:yjp.Information@1e643faf]" name="modify_Birthday" duration-ms="14781" started-at="2019-12-09T19:31:31Z" description="修改个人信息,生日" data-provider="birthday" finished-at="2019-12-09T19:31:46Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[E:\\1.jpeg]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[测试账号3]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[3]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[2018-11]]>
              </value>
            </param>
            <param index="4">
              <value>
                <![CDATA[操作失败]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
	expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
	expected [true] but found [false]
	at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:43)
	at yjp.Information.modify_Birthday(Information.java:88)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:822)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1130)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:113)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:206)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:177)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- modify_Birthday -->
        <test-method status="FAIL" signature="modify_Birthday(java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:yjp.Information@1e643faf]" name="modify_Birthday" duration-ms="14856" started-at="2019-12-09T19:31:46Z" description="修改个人信息,生日" data-provider="birthday" finished-at="2019-12-09T19:32:01Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[E:\\1.jpeg]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[测试账号3]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[3]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[]]>
              </value>
            </param>
            <param index="4">
              <value>
                <![CDATA[操作失败]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
	expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
	expected [true] but found [false]
	at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:43)
	at yjp.Information.modify_Birthday(Information.java:88)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:822)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1130)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:113)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:206)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:177)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- modify_Birthday -->
        <test-method status="FAIL" signature="modify_Img(java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:yjp.Information@1e643faf]" name="modify_Img" duration-ms="14558" started-at="2019-12-09T19:32:01Z" description="上传非图片文件" data-provider="img" finished-at="2019-12-09T19:32:16Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[E:\\1.jpeg]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[测试账号1]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[1]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[1999-10-04]]>
              </value>
            </param>
            <param index="4">
              <value>
                <![CDATA[操作失败]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
	expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
	expected [true] but found [false]
	at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:43)
	at yjp.Information.modify_Img(Information.java:111)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:822)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1130)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:113)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:206)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:177)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- modify_Img -->
        <test-method status="PASS" signature="modify_Name(java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:yjp.Information@1e643faf]" name="modify_Name" duration-ms="14809" started-at="2019-12-09T19:32:16Z" description="修改个人信息,昵称" data-provider="name" finished-at="2019-12-09T19:32:31Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[E:\\1.jpeg]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[测试账号1]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[1]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[1999-10-04]]>
              </value>
            </param>
            <param index="4">
              <value>
                <![CDATA[操作成功]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- modify_Name -->
        <test-method status="FAIL" signature="modify_Name(java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:yjp.Information@1e643faf]" name="modify_Name" duration-ms="14671" started-at="2019-12-09T19:32:31Z" description="修改个人信息,昵称" data-provider="name" finished-at="2019-12-09T19:32:45Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[E:\\1.jpeg]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[2]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[1999-10-05]]>
              </value>
            </param>
            <param index="4">
              <value>
                <![CDATA[操作失败]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
	expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
	expected [true] but found [false]
	at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:43)
	at yjp.Information.modify_Name(Information.java:66)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:822)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1130)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:113)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:206)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:177)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- modify_Name -->
        <test-method status="FAIL" signature="modify_Name(java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:yjp.Information@1e643faf]" name="modify_Name" duration-ms="14593" started-at="2019-12-09T19:32:45Z" description="修改个人信息,昵称" data-provider="name" finished-at="2019-12-09T19:33:00Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[E:\\1.jpeg]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[        ]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[2]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[1999-10-05]]>
              </value>
            </param>
            <param index="4">
              <value>
                <![CDATA[操作失败]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
	expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
	expected [true] but found [false]
	at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:43)
	at yjp.Information.modify_Name(Information.java:66)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:822)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1130)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:113)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:206)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:177)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- modify_Name -->
        <test-method status="PASS" signature="modify_Name(java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:yjp.Information@1e643faf]" name="modify_Name" duration-ms="15081" started-at="2019-12-09T19:33:00Z" description="修改个人信息,昵称" data-provider="name" finished-at="2019-12-09T19:33:15Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[E:\\1.jpeg]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[1]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[2]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[1999-10-05]]>
              </value>
            </param>
            <param index="4">
              <value>
                <![CDATA[操作成功]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- modify_Name -->
        <test-method status="PASS" signature="modify_Name(java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:yjp.Information@1e643faf]" name="modify_Name" duration-ms="14957" started-at="2019-12-09T19:33:15Z" description="修改个人信息,昵称" data-provider="name" finished-at="2019-12-09T19:33:30Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[E:\\1.jpeg]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[a]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[2]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[1999-10-05]]>
              </value>
            </param>
            <param index="4">
              <value>
                <![CDATA[操作成功]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- modify_Name -->
        <test-method status="PASS" signature="modify_Name(java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:yjp.Information@1e643faf]" name="modify_Name" duration-ms="14947" started-at="2019-12-09T19:33:30Z" description="修改个人信息,昵称" data-provider="name" finished-at="2019-12-09T19:33:45Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[E:\\1.jpeg]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[；]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[2]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[1999-10-05]]>
              </value>
            </param>
            <param index="4">
              <value>
                <![CDATA[操作成功]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- modify_Name -->
        <test-method status="PASS" signature="modify_Name(java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:yjp.Information@1e643faf]" name="modify_Name" duration-ms="14680" started-at="2019-12-09T19:33:45Z" description="修改个人信息,昵称" data-provider="name" finished-at="2019-12-09T19:34:00Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[E:\\1.jpeg]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[???????]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[1]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[1999-10-06]]>
              </value>
            </param>
            <param index="4">
              <value>
                <![CDATA[操作成功]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- modify_Name -->
        <test-method status="FAIL" signature="modify_Name(java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:yjp.Information@1e643faf]" name="modify_Name" duration-ms="3791" started-at="2019-12-09T19:34:00Z" description="修改个人信息,昵称" data-provider="name" finished-at="2019-12-09T19:34:03Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[E:\\2.jpeg]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[王然啊啊啊啊啊]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[2]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[1999-10-01]]>
              </value>
            </param>
            <param index="4">
              <value>
                <![CDATA[操作成功]]>
              </value>
            </param>
          </params>
          <exception class="org.openqa.selenium.InvalidArgumentException">
            <message>
              <![CDATA[File not found: E:\\2.jpeg
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:25:53'
System info: host: 'LAPTOP-GAD15EJN', ip: '169.254.0.95', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_73'
Driver info: org.openqa.selenium.firefox.FirefoxDriver
Capabilities {acceptInsecureCerts: true, browserName: firefox, browserVersion: 69.0.3, javascriptEnabled: true, moz:accessibilityChecks: false, moz:buildID: 20191009172106, moz:geckodriverVersion: 0.24.0, moz:headless: false, moz:processID: 19872, moz:profile: E:\Temp\rust_mozprofile.D7V..., moz:shutdownTimeout: 60000, moz:useNonSpecCompliantPointerOrigin: false, moz:webdriverClick: true, pageLoadStrategy: normal, platform: WINDOWS, platformName: WINDOWS, platformVersion: 10.0, rotatable: false, setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify}
Session ID: b43ad305-98b9-4435-ab91-fa87ea37d5f1]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.openqa.selenium.InvalidArgumentException: File not found: E:\\2.jpeg
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:25:53'
System info: host: 'LAPTOP-GAD15EJN', ip: '169.254.0.95', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_73'
Driver info: org.openqa.selenium.firefox.FirefoxDriver
Capabilities {acceptInsecureCerts: true, browserName: firefox, browserVersion: 69.0.3, javascriptEnabled: true, moz:accessibilityChecks: false, moz:buildID: 20191009172106, moz:geckodriverVersion: 0.24.0, moz:headless: false, moz:processID: 19872, moz:profile: E:\Temp\rust_mozprofile.D7V..., moz:shutdownTimeout: 60000, moz:useNonSpecCompliantPointerOrigin: false, moz:webdriverClick: true, pageLoadStrategy: normal, platform: WINDOWS, platformName: WINDOWS, platformVersion: 10.0, rotatable: false, setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify}
Session ID: b43ad305-98b9-4435-ab91-fa87ea37d5f1
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
	at java.lang.reflect.Constructor.newInstance(Unknown Source)
	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.createException(W3CHttpResponseCodec.java:187)
	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:122)
	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:49)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:158)
	at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:83)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:552)
	at org.openqa.selenium.remote.RemoteWebElement.execute(RemoteWebElement.java:285)
	at org.openqa.selenium.remote.RemoteWebElement.sendKeys(RemoteWebElement.java:106)
	at com.webtest.core.WebDriverEngine.typeAndClear(WebDriverEngine.java:133)
	at yjp.Information.modify_Name(Information.java:56)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:822)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1130)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:113)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:206)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:177)
]]>
            </full-stacktrace>
          </exception> <!-- org.openqa.selenium.InvalidArgumentException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- modify_Name -->
        <test-method status="FAIL" signature="modify_Success()[pri:0, instance:yjp.Information@1e643faf]" name="modify_Success" duration-ms="7398" started-at="2019-12-09T19:34:03Z" description="绑定邮箱成功" finished-at="2019-12-09T19:34:11Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at org.testng.Assert.assertTrue(Assert.java:52)
	at yjp.Information.modify_Success(Information.java:132)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:822)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1130)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:113)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:206)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:177)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- modify_Success -->
        <test-method status="PASS" signature="doAfterMethod()[pri:0, instance:yjp.Information@1e643faf]" name="doAfterMethod" is-config="true" duration-ms="3151" started-at="2019-12-09T19:34:11Z" finished-at="2019-12-09T19:34:14Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- doAfterMethod -->
      </class> <!-- yjp.Information -->
      <class name="yjp.SecuritySet">
        <test-method status="PASS" signature="doBeforeClass()[pri:0, instance:yjp.SecuritySet@7a79be86]" name="doBeforeClass" is-config="true" duration-ms="7007" started-at="2019-12-09T19:35:14Z" finished-at="2019-12-09T19:35:21Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- doBeforeClass -->
        <test-method status="PASS" signature="setup()[pri:0, instance:yjp.SecuritySet@7a79be86]" name="setup" is-config="true" duration-ms="39724" started-at="2019-12-09T19:35:21Z" description="登录" finished-at="2019-12-09T19:36:00Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method status="PASS" signature="GetVerifCode()[pri:0, instance:yjp.SecuritySet@7a79be86]" name="GetVerifCode" duration-ms="15615" started-at="2019-12-09T19:36:00Z" description="修改支付密码，获取验证码" finished-at="2019-12-09T19:36:16Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- GetVerifCode -->
        <test-method status="PASS" signature="ModifyPassword_Success()[pri:0, instance:yjp.SecuritySet@7a79be86]" name="ModifyPassword_Success" duration-ms="14547" started-at="2019-12-09T19:36:16Z" description="修改支付密码成功" finished-at="2019-12-09T19:36:31Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- ModifyPassword_Success -->
        <test-method status="FAIL" signature="ModifyPswVerifCode_Fail()[pri:0, instance:yjp.SecuritySet@7a79be86]" name="ModifyPswVerifCode_Fail" duration-ms="1098" started-at="2019-12-09T19:36:31Z" description="修改支付密码，验证码错误" finished-at="2019-12-09T19:36:32Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at org.testng.Assert.assertTrue(Assert.java:52)
	at yjp.SecuritySet.ModifyPswVerifCode_Fail(SecuritySet.java:97)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:822)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1130)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:113)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:206)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:177)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- ModifyPswVerifCode_Fail -->
        <test-method status="FAIL" signature="changePsw_Success()[pri:0, instance:yjp.SecuritySet@7a79be86]" name="changePsw_Success" duration-ms="11056" started-at="2019-12-09T19:36:32Z" description="更改登录密码成功" finished-at="2019-12-09T19:36:43Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
	expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
	expected [true] but found [false]
	at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:43)
	at yjp.SecuritySet.changePsw_Success(SecuritySet.java:49)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:822)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1130)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:113)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:206)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:177)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- changePsw_Success -->
        <test-method status="FAIL" signature="mailtest()[pri:0, instance:yjp.SecuritySet@7a79be86]" name="mailtest" duration-ms="921" started-at="2019-12-09T19:36:43Z" description="邮箱验证成功" finished-at="2019-12-09T19:36:44Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at org.testng.Assert.assertTrue(Assert.java:52)
	at yjp.SecuritySet.mailtest(SecuritySet.java:119)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:822)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1130)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:113)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:206)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:177)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- mailtest -->
        <test-method status="FAIL" signature="phoneCheck()[pri:0, instance:yjp.SecuritySet@7a79be86]" name="phoneCheck" duration-ms="396" started-at="2019-12-09T19:36:44Z" description="更改手机验证失败，新手机号输入为中文" finished-at="2019-12-09T19:36:44Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at org.testng.Assert.assertTrue(Assert.java:52)
	at yjp.SecuritySet.phoneCheck(SecuritySet.java:73)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:822)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1130)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:113)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:206)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:177)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- phoneCheck -->
        <test-method status="PASS" signature="phoneCheck_Fail1()[pri:0, instance:yjp.SecuritySet@7a79be86]" name="phoneCheck_Fail1" duration-ms="14603" started-at="2019-12-09T19:36:44Z" description="更改手机验证失败，新手机号位数不足" finished-at="2019-12-09T19:36:59Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- phoneCheck_Fail1 -->
        <test-method status="PASS" signature="doAfterMethod()[pri:0, instance:yjp.SecuritySet@7a79be86]" name="doAfterMethod" is-config="true" duration-ms="5467" started-at="2019-12-09T19:36:59Z" finished-at="2019-12-09T19:37:04Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- doAfterMethod -->
      </class> <!-- yjp.SecuritySet -->
      <class name="yjp.Evaluation">
        <test-method status="PASS" signature="doBeforeClass()[pri:0, instance:yjp.Evaluation@3b6eb2ec]" name="doBeforeClass" is-config="true" duration-ms="6534" started-at="2019-12-09T19:28:40Z" finished-at="2019-12-09T19:28:46Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- doBeforeClass -->
        <test-method status="PASS" signature="setup()[pri:0, instance:yjp.Evaluation@3b6eb2ec]" name="setup" is-config="true" duration-ms="40860" started-at="2019-12-09T19:28:46Z" description="登录" finished-at="2019-12-09T19:29:27Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method status="PASS" signature="seeEval()[pri:1, instance:yjp.Evaluation@3b6eb2ec]" name="seeEval" duration-ms="3778" started-at="2019-12-09T19:29:27Z" description="已评论区查看商品评论" finished-at="2019-12-09T19:29:31Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- seeEval -->
        <test-method status="PASS" signature="eval()[pri:3, instance:yjp.Evaluation@3b6eb2ec]" name="eval" duration-ms="7785" started-at="2019-12-09T19:29:31Z" description="对待评论订单进行评论" finished-at="2019-12-09T19:29:39Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- eval -->
        <test-method status="PASS" signature="doAfterMethod()[pri:0, instance:yjp.Evaluation@3b6eb2ec]" name="doAfterMethod" is-config="true" duration-ms="2999" started-at="2019-12-09T19:29:39Z" finished-at="2019-12-09T19:29:42Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- doAfterMethod -->
      </class> <!-- yjp.Evaluation -->
      <class name="yjp.AddressMag">
        <test-method status="PASS" signature="doBeforeClass()[pri:0, instance:yjp.AddressMag@34ce8af7]" name="doBeforeClass" is-config="true" duration-ms="6472" started-at="2019-12-09T19:37:04Z" finished-at="2019-12-09T19:37:11Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- doBeforeClass -->
        <test-method status="PASS" signature="setup()[pri:0, instance:yjp.AddressMag@34ce8af7]" name="setup" is-config="true" duration-ms="35068" started-at="2019-12-09T19:37:11Z" description="登录" finished-at="2019-12-09T19:37:46Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method status="PASS" signature="del()[pri:0, instance:yjp.AddressMag@34ce8af7]" name="del" duration-ms="7119" started-at="2019-12-09T19:37:46Z" description="删除地址" finished-at="2019-12-09T19:37:53Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- del -->
        <test-method status="PASS" signature="modify_Success1()[pri:0, instance:yjp.AddressMag@34ce8af7]" name="modify_Success1" duration-ms="10901" started-at="2019-12-09T19:37:53Z" description="修改地址成功" finished-at="2019-12-09T19:38:04Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- modify_Success1 -->
        <test-method status="PASS" signature="setDefault()[pri:0, instance:yjp.AddressMag@34ce8af7]" name="setDefault" duration-ms="7282" started-at="2019-12-09T19:38:04Z" description="设置为默认地址" finished-at="2019-12-09T19:38:11Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setDefault -->
        <test-method status="PASS" signature="doAfterMethod()[pri:0, instance:yjp.AddressMag@34ce8af7]" name="doAfterMethod" is-config="true" duration-ms="3802" started-at="2019-12-09T19:38:11Z" finished-at="2019-12-09T19:38:15Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- doAfterMethod -->
      </class> <!-- yjp.AddressMag -->
      <class name="yjp.Notice">
        <test-method status="PASS" signature="doBeforeClass()[pri:0, instance:yjp.Notice@6e8dacdf]" name="doBeforeClass" is-config="true" duration-ms="7573" started-at="2019-12-09T19:34:14Z" finished-at="2019-12-09T19:34:21Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- doBeforeClass -->
        <test-method status="PASS" signature="setup()[pri:0, instance:yjp.Notice@6e8dacdf]" name="setup" is-config="true" duration-ms="40274" started-at="2019-12-09T19:34:21Z" description="登录" finished-at="2019-12-09T19:35:02Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method status="PASS" signature="delOne()[pri:1, instance:yjp.Notice@6e8dacdf]" name="delOne" duration-ms="7529" started-at="2019-12-09T19:35:02Z" description="删除一条通知消息" finished-at="2019-12-09T19:35:09Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- delOne -->
        <test-method status="FAIL" signature="details()[pri:2, instance:yjp.Notice@6e8dacdf]" name="details" duration-ms="31" started-at="2019-12-09T19:35:09Z" description="选择一条通知消息，点击查看详情" finished-at="2019-12-09T19:35:09Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at org.testng.Assert.assertTrue(Assert.java:52)
	at yjp.Notice.details(Notice.java:45)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:822)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1130)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:113)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:206)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:177)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- details -->
        <test-method status="PASS" signature="doAfterMethod()[pri:0, instance:yjp.Notice@6e8dacdf]" name="doAfterMethod" is-config="true" duration-ms="4375" started-at="2019-12-09T19:35:09Z" finished-at="2019-12-09T19:35:14Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- doAfterMethod -->
      </class> <!-- yjp.Notice -->
      <class name="yjp.AddAddress">
        <test-method status="PASS" signature="doBeforeClass()[pri:0, instance:yjp.AddAddress@6a5fc7f7]" name="doBeforeClass" is-config="true" duration-ms="7804" started-at="2019-12-09T19:26:41Z" finished-at="2019-12-09T19:26:49Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- doBeforeClass -->
        <test-method status="PASS" signature="setup()[pri:0, instance:yjp.AddAddress@6a5fc7f7]" name="setup" is-config="true" duration-ms="43070" started-at="2019-12-09T19:26:49Z" description="登录" finished-at="2019-12-09T19:27:32Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method status="PASS" signature="addAddress_Fail1(java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:yjp.AddAddress@6a5fc7f7]" name="addAddress_Fail1" duration-ms="5802" started-at="2019-12-09T19:27:33Z" description="增加新地址失败，缺少必填信息" data-provider="缺少必填信息" finished-at="2019-12-09T19:27:39Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[15233611111]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[辽宁省]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[大连市]]>
              </value>
            </param>
            <param index="4">
              <value>
                <![CDATA[中山区]]>
              </value>
            </param>
            <param index="5">
              <value>
                <![CDATA[海军广场街道]]>
              </value>
            </param>
            <param index="6">
              <value>
                <![CDATA[1楼202]]>
              </value>
            </param>
            <param index="7">
              <value>
                <![CDATA[000001]]>
              </value>
            </param>
            <param index="8">
              <value>
                <![CDATA[收货人不能为空]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- addAddress_Fail1 -->
        <test-method status="FAIL" signature="addAddress_Fail1(java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:yjp.AddAddress@6a5fc7f7]" name="addAddress_Fail1" duration-ms="4750" started-at="2019-12-09T19:27:39Z" description="增加新地址失败，缺少必填信息" data-provider="缺少必填信息" finished-at="2019-12-09T19:27:44Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[A先生]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[辽宁省]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[大连市]]>
              </value>
            </param>
            <param index="4">
              <value>
                <![CDATA[中山区]]>
              </value>
            </param>
            <param index="5">
              <value>
                <![CDATA[海军广场街道]]>
              </value>
            </param>
            <param index="6">
              <value>
                <![CDATA[1楼203]]>
              </value>
            </param>
            <param index="7">
              <value>
                <![CDATA[000002]]>
              </value>
            </param>
            <param index="8">
              <value>
                <![CDATA[ 手机号不能为空]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
	expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
	expected [true] but found [false]
	at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:43)
	at yjp.AddAddress.addAddress_Fail1(AddAddress.java:83)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:822)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1130)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:113)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:206)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:177)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- addAddress_Fail1 -->
        <test-method status="FAIL" signature="addAddress_Fail1(java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:yjp.AddAddress@6a5fc7f7]" name="addAddress_Fail1" duration-ms="275" started-at="2019-12-09T19:27:44Z" description="增加新地址失败，缺少必填信息" data-provider="缺少必填信息" finished-at="2019-12-09T19:27:44Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[A先生]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[15233611111]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[辽宁省]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[大连市]]>
              </value>
            </param>
            <param index="4">
              <value>
                <![CDATA[]]>
              </value>
            </param>
            <param index="5">
              <value>
                <![CDATA[]]>
              </value>
            </param>
            <param index="6">
              <value>
                <![CDATA[1楼204]]>
              </value>
            </param>
            <param index="7">
              <value>
                <![CDATA[000003]]>
              </value>
            </param>
            <param index="8">
              <value>
                <![CDATA[请选择镇/区]]>
              </value>
            </param>
          </params>
          <exception class="org.openqa.selenium.NoSuchElementException">
            <message>
              <![CDATA[Cannot locate element with text: 
For documentation on this error, please visit: https://www.seleniumhq.org/exceptions/no_such_element.html
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:25:53'
System info: host: 'LAPTOP-GAD15EJN', ip: '169.254.0.95', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_73'
Driver info: driver.version: unknown]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.openqa.selenium.NoSuchElementException: Cannot locate element with text: 
For documentation on this error, please visit: https://www.seleniumhq.org/exceptions/no_such_element.html
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:25:53'
System info: host: 'LAPTOP-GAD15EJN', ip: '169.254.0.95', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_73'
Driver info: driver.version: unknown
	at org.openqa.selenium.support.ui.Select.selectByVisibleText(Select.java:147)
	at com.webtest.core.WebDriverEngine.selectByVisibleText(WebDriverEngine.java:249)
	at yjp.AddAddress.addAddress_Fail1(AddAddress.java:75)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:822)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1130)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:113)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:206)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:177)
]]>
            </full-stacktrace>
          </exception> <!-- org.openqa.selenium.NoSuchElementException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- addAddress_Fail1 -->
        <test-method status="FAIL" signature="addAddress_Fail1(java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:yjp.AddAddress@6a5fc7f7]" name="addAddress_Fail1" duration-ms="298" started-at="2019-12-09T19:27:44Z" description="增加新地址失败，缺少必填信息" data-provider="缺少必填信息" finished-at="2019-12-09T19:27:44Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[A先生]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[15233611111]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[辽宁省]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[大连市]]>
              </value>
            </param>
            <param index="4">
              <value>
                <![CDATA[中山区]]>
              </value>
            </param>
            <param index="5">
              <value>
                <![CDATA[]]>
              </value>
            </param>
            <param index="6">
              <value>
                <![CDATA[1楼205]]>
              </value>
            </param>
            <param index="7">
              <value>
                <![CDATA[000004]]>
              </value>
            </param>
            <param index="8">
              <value>
                <![CDATA[保存]]>
              </value>
            </param>
          </params>
          <exception class="org.openqa.selenium.NoSuchElementException">
            <message>
              <![CDATA[Cannot locate element with text: 
For documentation on this error, please visit: https://www.seleniumhq.org/exceptions/no_such_element.html
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:25:53'
System info: host: 'LAPTOP-GAD15EJN', ip: '169.254.0.95', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_73'
Driver info: driver.version: unknown]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.openqa.selenium.NoSuchElementException: Cannot locate element with text: 
For documentation on this error, please visit: https://www.seleniumhq.org/exceptions/no_such_element.html
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:25:53'
System info: host: 'LAPTOP-GAD15EJN', ip: '169.254.0.95', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_73'
Driver info: driver.version: unknown
	at org.openqa.selenium.support.ui.Select.selectByVisibleText(Select.java:147)
	at com.webtest.core.WebDriverEngine.selectByVisibleText(WebDriverEngine.java:249)
	at yjp.AddAddress.addAddress_Fail1(AddAddress.java:76)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:822)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1130)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:113)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:206)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:177)
]]>
            </full-stacktrace>
          </exception> <!-- org.openqa.selenium.NoSuchElementException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- addAddress_Fail1 -->
        <test-method status="PASS" signature="addAddress_Fail1(java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:yjp.AddAddress@6a5fc7f7]" name="addAddress_Fail1" duration-ms="4738" started-at="2019-12-09T19:27:44Z" description="增加新地址失败，缺少必填信息" data-provider="缺少必填信息" finished-at="2019-12-09T19:27:49Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[A先生]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[15233611111]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[辽宁省]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[大连市]]>
              </value>
            </param>
            <param index="4">
              <value>
                <![CDATA[中山区]]>
              </value>
            </param>
            <param index="5">
              <value>
                <![CDATA[海军广场街道]]>
              </value>
            </param>
            <param index="6">
              <value>
                <![CDATA[]]>
              </value>
            </param>
            <param index="7">
              <value>
                <![CDATA[000005]]>
              </value>
            </param>
            <param index="8">
              <value>
                <![CDATA[地址不能为空]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- addAddress_Fail1 -->
        <test-method status="PASS" signature="addAddress_Fail2(java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:yjp.AddAddress@6a5fc7f7]" name="addAddress_Fail2" duration-ms="4683" started-at="2019-12-09T19:27:49Z" description="增加新地址失败，手机或固定电话格式错误" data-provider="手机或固定电话格式错误" finished-at="2019-12-09T19:27:54Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[杨测试]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[1523361111]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[辽宁省]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[大连市]]>
              </value>
            </param>
            <param index="4">
              <value>
                <![CDATA[中山区]]>
              </value>
            </param>
            <param index="5">
              <value>
                <![CDATA[海军广场街道]]>
              </value>
            </param>
            <param index="6">
              <value>
                <![CDATA[1楼202]]>
              </value>
            </param>
            <param index="7">
              <value>
                <![CDATA[000001]]>
              </value>
            </param>
            <param index="8">
              <value>
                <![CDATA[手机号码格式有误]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- addAddress_Fail2 -->
        <test-method status="PASS" signature="addAddress_Fail2(java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:yjp.AddAddress@6a5fc7f7]" name="addAddress_Fail2" duration-ms="4747" started-at="2019-12-09T19:27:54Z" description="增加新地址失败，手机或固定电话格式错误" data-provider="手机或固定电话格式错误" finished-at="2019-12-09T19:27:59Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[杨测试]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[1523361111111]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[辽宁省]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[大连市]]>
              </value>
            </param>
            <param index="4">
              <value>
                <![CDATA[中山区]]>
              </value>
            </param>
            <param index="5">
              <value>
                <![CDATA[海军广场街道]]>
              </value>
            </param>
            <param index="6">
              <value>
                <![CDATA[1楼203]]>
              </value>
            </param>
            <param index="7">
              <value>
                <![CDATA[000002]]>
              </value>
            </param>
            <param index="8">
              <value>
                <![CDATA[手机号码格式有误]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- addAddress_Fail2 -->
        <test-method status="PASS" signature="addAddress_Fail2(java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:yjp.AddAddress@6a5fc7f7]" name="addAddress_Fail2" duration-ms="4745" started-at="2019-12-09T19:27:59Z" description="增加新地址失败，手机或固定电话格式错误" data-provider="手机或固定电话格式错误" finished-at="2019-12-09T19:28:03Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[杨测试]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[aaaa]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[辽宁省]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[大连市]]>
              </value>
            </param>
            <param index="4">
              <value>
                <![CDATA[中山区]]>
              </value>
            </param>
            <param index="5">
              <value>
                <![CDATA[海军广场街道]]>
              </value>
            </param>
            <param index="6">
              <value>
                <![CDATA[1楼204]]>
              </value>
            </param>
            <param index="7">
              <value>
                <![CDATA[000003]]>
              </value>
            </param>
            <param index="8">
              <value>
                <![CDATA[手机号码格式有误]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- addAddress_Fail2 -->
        <test-method status="FAIL" signature="addAddress_Fail2(java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:yjp.AddAddress@6a5fc7f7]" name="addAddress_Fail2" duration-ms="4803" started-at="2019-12-09T19:28:03Z" description="增加新地址失败，手机或固定电话格式错误" data-provider="手机或固定电话格式错误" finished-at="2019-12-09T19:28:08Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[杨测试]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[辽宁省]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[大连市]]>
              </value>
            </param>
            <param index="4">
              <value>
                <![CDATA[中山区]]>
              </value>
            </param>
            <param index="5">
              <value>
                <![CDATA[海军广场街道]]>
              </value>
            </param>
            <param index="6">
              <value>
                <![CDATA[1楼205]]>
              </value>
            </param>
            <param index="7">
              <value>
                <![CDATA[000004]]>
              </value>
            </param>
            <param index="8">
              <value>
                <![CDATA[手机号码格式有误]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
	expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
	expected [true] but found [false]
	at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:43)
	at yjp.AddAddress.addAddress_Fail2(AddAddress.java:111)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:822)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1130)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:113)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:206)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:177)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- addAddress_Fail2 -->
        <test-method status="PASS" signature="addAddress_Fail2(java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:yjp.AddAddress@6a5fc7f7]" name="addAddress_Fail2" duration-ms="4759" started-at="2019-12-09T19:28:08Z" description="增加新地址失败，手机或固定电话格式错误" data-provider="手机或固定电话格式错误" finished-at="2019-12-09T19:28:13Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[杨测试]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[           ]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[辽宁省]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[大连市]]>
              </value>
            </param>
            <param index="4">
              <value>
                <![CDATA[中山区]]>
              </value>
            </param>
            <param index="5">
              <value>
                <![CDATA[海军广场街道]]>
              </value>
            </param>
            <param index="6">
              <value>
                <![CDATA[1楼206]]>
              </value>
            </param>
            <param index="7">
              <value>
                <![CDATA[000005]]>
              </value>
            </param>
            <param index="8">
              <value>
                <![CDATA[手机号码格式有误]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- addAddress_Fail2 -->
        <test-method status="PASS" signature="addAddress_Fail2(java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:yjp.AddAddress@6a5fc7f7]" name="addAddress_Fail2" duration-ms="4811" started-at="2019-12-09T19:28:13Z" description="增加新地址失败，手机或固定电话格式错误" data-provider="手机或固定电话格式错误" finished-at="2019-12-09T19:28:18Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[杨测试]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[!!!!!!!!!!!]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[辽宁省]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[大连市]]>
              </value>
            </param>
            <param index="4">
              <value>
                <![CDATA[中山区]]>
              </value>
            </param>
            <param index="5">
              <value>
                <![CDATA[海军广场街道]]>
              </value>
            </param>
            <param index="6">
              <value>
                <![CDATA[1楼207]]>
              </value>
            </param>
            <param index="7">
              <value>
                <![CDATA[000006]]>
              </value>
            </param>
            <param index="8">
              <value>
                <![CDATA[手机号码格式有误]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- addAddress_Fail2 -->
        <test-method status="FAIL" signature="addAddress_Fail2(java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:yjp.AddAddress@6a5fc7f7]" name="addAddress_Fail2" duration-ms="4823" started-at="2019-12-09T19:28:18Z" description="增加新地址失败，手机或固定电话格式错误" data-provider="手机或固定电话格式错误" finished-at="2019-12-09T19:28:23Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[杨测试]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[辽宁省]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[大连市]]>
              </value>
            </param>
            <param index="4">
              <value>
                <![CDATA[中山区]]>
              </value>
            </param>
            <param index="5">
              <value>
                <![CDATA[海军广场街道]]>
              </value>
            </param>
            <param index="6">
              <value>
                <![CDATA[1楼208]]>
              </value>
            </param>
            <param index="7">
              <value>
                <![CDATA[000007]]>
              </value>
            </param>
            <param index="8">
              <value>
                <![CDATA[手机号码格式有误]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
	expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
	expected [true] but found [false]
	at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:43)
	at yjp.AddAddress.addAddress_Fail2(AddAddress.java:111)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:822)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1130)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:113)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:206)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:177)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- addAddress_Fail2 -->
        <test-method status="PASS" signature="addAddress_Fail2(java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:yjp.AddAddress@6a5fc7f7]" name="addAddress_Fail2" duration-ms="4809" started-at="2019-12-09T19:28:23Z" description="增加新地址失败，手机或固定电话格式错误" data-provider="手机或固定电话格式错误" finished-at="2019-12-09T19:28:27Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[杨测试]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[测试]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[辽宁省]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[大连市]]>
              </value>
            </param>
            <param index="4">
              <value>
                <![CDATA[中山区]]>
              </value>
            </param>
            <param index="5">
              <value>
                <![CDATA[海军广场街道]]>
              </value>
            </param>
            <param index="6">
              <value>
                <![CDATA[1楼202]]>
              </value>
            </param>
            <param index="7">
              <value>
                <![CDATA[000001]]>
              </value>
            </param>
            <param index="8">
              <value>
                <![CDATA[手机号码格式有误]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- addAddress_Fail2 -->
        <test-method status="PASS" signature="addAddress_Fail2(java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:yjp.AddAddress@6a5fc7f7]" name="addAddress_Fail2" duration-ms="4834" started-at="2019-12-09T19:28:27Z" description="增加新地址失败，手机或固定电话格式错误" data-provider="手机或固定电话格式错误" finished-at="2019-12-09T19:28:32Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[杨测试]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[???????]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[辽宁省]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[大连市]]>
              </value>
            </param>
            <param index="4">
              <value>
                <![CDATA[中山区]]>
              </value>
            </param>
            <param index="5">
              <value>
                <![CDATA[海军广场街道]]>
              </value>
            </param>
            <param index="6">
              <value>
                <![CDATA[1楼203]]>
              </value>
            </param>
            <param index="7">
              <value>
                <![CDATA[000002]]>
              </value>
            </param>
            <param index="8">
              <value>
                <![CDATA[手机号码格式有误]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- addAddress_Fail2 -->
        <test-method status="PASS" signature="addAddress_Success(java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:yjp.AddAddress@6a5fc7f7]" name="addAddress_Success" duration-ms="3722" started-at="2019-12-09T19:28:32Z" description="成功添加一条新地址" data-provider="成功添加" finished-at="2019-12-09T19:28:36Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[王先生]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[15233611112]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[辽宁省]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[大连市]]>
              </value>
            </param>
            <param index="4">
              <value>
                <![CDATA[中山区]]>
              </value>
            </param>
            <param index="5">
              <value>
                <![CDATA[海军广场街道]]>
              </value>
            </param>
            <param index="6">
              <value>
                <![CDATA[1楼202]]>
              </value>
            </param>
            <param index="7">
              <value>
                <![CDATA[000001]]>
              </value>
            </param>
            <param index="8">
              <value>
                <![CDATA[王先生]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- addAddress_Success -->
        <test-method status="PASS" signature="doAfterMethod()[pri:0, instance:yjp.AddAddress@6a5fc7f7]" name="doAfterMethod" is-config="true" duration-ms="3779" started-at="2019-12-09T19:28:36Z" finished-at="2019-12-09T19:28:40Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- doAfterMethod -->
      </class> <!-- yjp.AddAddress -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
