<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="LAPTOP-KG4V20B1" name="lixiaoyue.Test_GongYingShang" tests="25" failures="5" timestamp="10 Dec 2019 09:43:55 GMT" time="440.412" errors="0">
  <testcase name="GetPot" time="23.243" classname="lixiaoyue.Test_GongYingShang"/>
  <testcase name="GetPot" time="23.431" classname="lixiaoyue.Test_GongYingShang"/>
  <testcase name="Commodity" time="6.810" classname="lixiaoyue.Test_GongYingShang"/>
  <testcase name="GetPot" time="23.586" classname="lixiaoyue.Test_GongYingShang">
    <failure type="java.lang.AssertionError" message="expected:&lt;��¼���벻��Ϊ��&gt; but was:&lt;�û�Ա�Ѿ��ǹ�Ӧ��&gt;">
      <![CDATA[java.lang.AssertionError: expected:<��¼���벻��Ϊ��> but was:<�û�Ա�Ѿ��ǹ�Ӧ��>
	at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:101)
	at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:108)
	at lixiaoyue.Test_GongYingShang.GetPot(Test_GongYingShang.java:71)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:822)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1130)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:113)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:206)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:177)
]]>
    </failure>
  </testcase> <!-- GetPot -->
  <testcase name="GetPot" time="26.383" classname="lixiaoyue.Test_GongYingShang"/>
  <testcase name="GetPot" time="23.284" classname="lixiaoyue.Test_GongYingShang">
    <failure type="java.lang.AssertionError" message="expected:&lt;��Ӧ�����Ʋ���Ϊ��&gt; but was:&lt;������ͬ�Ĺ�Ӧ���˺�&gt;">
      <![CDATA[java.lang.AssertionError: expected:<��Ӧ�����Ʋ���Ϊ��> but was:<������ͬ�Ĺ�Ӧ���˺�>
	at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:101)
	at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:108)
	at lixiaoyue.Test_GongYingShang.GetPot(Test_GongYingShang.java:71)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:822)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1130)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:113)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:206)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:177)
]]>
    </failure>
  </testcase> <!-- GetPot -->
  <testcase name="GetPot" time="26.444" classname="lixiaoyue.Test_GongYingShang"/>
  <testcase name="Transfer" time="7.869" classname="lixiaoyue.Test_GongYingShang"/>
  <testcase name="List" time="7.782" classname="lixiaoyue.Test_GongYingShang"/>
  <testcase name="GetPot" time="26.810" classname="lixiaoyue.Test_GongYingShang">
    <failure type="java.lang.AssertionError" message="expected:&lt;��Ա�˺ű���&gt; but was:&lt;�û�Ա�Ѿ��ǹ�Ӧ��&gt;">
      <![CDATA[java.lang.AssertionError: expected:<��Ա�˺ű���> but was:<�û�Ա�Ѿ��ǹ�Ӧ��>
	at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:101)
	at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:108)
	at lixiaoyue.Test_GongYingShang.GetPot(Test_GongYingShang.java:71)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:822)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1130)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:113)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:206)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:177)
]]>
    </failure>
  </testcase> <!-- GetPot -->
  <testcase name="GetPot" time="26.639" classname="lixiaoyue.Test_GongYingShang"/>
  <testcase name="Order" time="6.756" classname="lixiaoyue.Test_GongYingShang"/>
  <testcase name="Settlement" time="7.774" classname="lixiaoyue.Test_GongYingShang"/>
  <testcase name="GetPot" time="26.962" classname="lixiaoyue.Test_GongYingShang"/>
  <testcase name="Entry" time="16.897" classname="lixiaoyue.Test_GongYingShang"/>
  <testcase name="GetPot" time="17.057" classname="lixiaoyue.Test_GongYingShang"/>
  <testcase name="List2" time="6.739" classname="lixiaoyue.Test_GongYingShang"/>
  <testcase name="GetPot" time="23.521" classname="lixiaoyue.Test_GongYingShang"/>
  <testcase name="GetPot" time="23.120" classname="lixiaoyue.Test_GongYingShang"/>
  <testcase name="GetPot" time="26.706" classname="lixiaoyue.Test_GongYingShang">
    <failure type="java.lang.AssertionError" message="expected:&lt;��ӳɹ�&gt; but was:&lt;��Ӧ�̺�̨�˺Ų���Ϊ��&gt;">
      <![CDATA[java.lang.AssertionError: expected:<��ӳɹ�> but was:<��Ӧ�̺�̨�˺Ų���Ϊ��>
	at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:101)
	at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:108)
	at lixiaoyue.Test_GongYingShang.GetPot(Test_GongYingShang.java:71)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:822)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1130)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:113)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:206)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:177)
]]>
    </failure>
  </testcase> <!-- GetPot -->
  <testcase name="Goods" time="8.764" classname="lixiaoyue.Test_GongYingShang"/>
  <testcase name="GetPot" time="17.023" classname="lixiaoyue.Test_GongYingShang">
    <failure type="java.lang.AssertionError" message="expected:&lt;���������&gt; but was:&lt;��ӳɹ�&gt;">
      <![CDATA[java.lang.AssertionError: expected:<���������> but was:<��ӳɹ�>
	at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:101)
	at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:108)
	at lixiaoyue.Test_GongYingShang.GetPot(Test_GongYingShang.java:71)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:822)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1130)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:113)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:206)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:177)
]]>
    </failure>
  </testcase> <!-- GetPot -->
  <testcase name="GetPot" time="20.300" classname="lixiaoyue.Test_GongYingShang"/>
  <testcase name="Apply" time="7.774" classname="lixiaoyue.Test_GongYingShang"/>
  <testcase name="Refund" time="8.738" classname="lixiaoyue.Test_GongYingShang"/>
</testsuite> <!-- lixiaoyue.Test_GongYingShang -->
